name: .NET

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Setup for Test Docs
      run: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
    - name: Generate Test Docs
      run: livingdoc test-assembly dotnetexample-test/bin/Debug/net6.0/dotnetexample-test.dll -t dotnetexample-test/bin/Debug/net6.0/TestExecution.json -o test-results/TestOutput.html
    - name: Publish Tests
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/develop'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./test-results